language: elixir
elixir: '1.9.0'
otp_release: '20.1'

services:
  - postgresql

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libssl1.0.0 postgresql-client
  - sudo apt-get autoclean

#stages:
  #- compile
  #- test
  #- name: deploy
    #if: branch = deployment

jobs:
  include:
    - stage: test
      #before_script:
      script:
        - cp config/test.travis.exs config/test.exs
        - MIX_ENV=test mix ecto.create
        - MIX_ENV=test mix ecto.migrate
        - MIX_ENV=test mix run priv/repo/seeds.exs
        - MIX_ENV=test mix espec
    #- stage: deploy
      #script: ./scripts/deploy.sh

#compile:
  #provider: script
  #script: mix compile

#deploy:
  #provider: script
  #script: ./scripts/deploy.sh
