language: elixir
elixir: '1.9.0'
otp_release: '20.1'

notifications:
  email:
    if: branch = release
    on_success: always
    on_failure: always

services:
  - postgresql

stages:
  - test
  - name: build
    if: branch = release

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev postgresql-client
  - sudo apt-get autoclean

jobs:
  include:
    - stage: test
      before_script:
        - cp config/test.travis.exs config/test.exs
        - MIX_ENV=test mix ecto.create
        - MIX_ENV=test mix ecto.migrate
      script:
        - MIX_ENV=test mix espec
    - stage: build
      script: ./scripts/build.sh
