dist: focal # Ubuntu 20.04
language: elixir
elixir: '1.9.4'
otp_release: '22.3' # https://docs.travis-ci.com/user/languages/erlang/#otprelease-versions

notifications:
  email:
    if: branch = release
    on_success: always
    on_failure: always

services:
  - postgresql

stages:
  - test
  - name: build
    if: branch = release

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libssl1.0.0 postgresql-client
  - sudo apt-get autoclean

jobs:
  include:
    - stage: test
      before_script:
        - cp config/test.travis.exs config/test.exs
        - MIX_ENV=test mix ecto.create
        - MIX_ENV=test mix ecto.migrate
      script:
        - MIX_ENV=test mix espec
    - stage: build
      script: ./scripts/build.sh
